name: release-please

on:
  workflow_call:
    outputs:
      release_created:
        description: "Set if the release has been created"
        value: ${{ jobs.release-please.outputs.release_created }}
      tag_name:
        description: "The tag name"
        value: ${{ jobs.release-please.outputs.tag_name }}
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
