name: test

on:
  push:
    branches:
      - "!main"
  pull_request:
  workflow_call:

jobs:
  test-implementation-job:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action step
        uses: ./ # Uses an action in the root directory
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: AndreasAugustin/template.git
          is_dry_run: true
